pull_request_rules:
  - name: ✔️ Automatic merge on pull request approval
    conditions:
      - approved-reviews-by>=1
      - check-success=CodeQL
      - check-success=GitGuardian Security Checks
      - check-success=Vercel
    actions:
      merge:
        method: merge
      comment:
        message: ✔️ Automatic merge on pull request approval
  - name: 📦 Automatic merge on @dependabot pull request (low priority)
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - label=dependencies
      - check-success=CodeQL
      - check-success=GitGuardian Security Checks
      - check-success=Vercel
    actions:
      merge:
        method: merge
        strict: smart
        priority: low
      comment:
        message: 📦 Automatic merge on @dependabot pull request (low priority)
